
print("---------------------")
print("|                    |")
print("|                    |")
print("|                    |")
print("|                    |")
print("|                    |")
print("----------------------")
print("         /| ")
print("        /  |")
print("       /    |")
print("      /      |")
print("     /        |")
print("    /           |")
print("   /______________|")
#making a circle
